title: "Ceylon Reef"
email: "ceylonreef@gmail.com"
author: Yoosuf
description: > # this means to ignore newlines until "baseurl:"
  Ceylon Reef sells the best aquarium equipment, nutrition and supplements the world has to offer. Take your tank from ordinary to extraordinary today!

show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ceylonreef.com" # the base hostname & protocol for your site, e.g. http://example.com


twitter_username: ceylonreef
facebook_username:  ceylonreef
instagram_username:  ceylonreef

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock


header_pages:
- consultancy.markdown
- store.markdown
- posts.markdown
- about.markdown
- contact.markdown


google_analytics: UA-127083378-1

gems:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap


collections:
  resources:
    output: true
  products:
    output: true
